version: 2.1

jobs:
  test-ubuntu-lunar-kicad6:
    docker:
      - image: admwscki/kicad-kbplacer-primary:6.0.11-lunar
    steps: &in-docker-test-steps
      - checkout
      - run:
          name: Prepare tests
          command: |
            pip3 install --no-cache-dir -r dev-requirements.txt
      - run:
          name: Run tests
          command: |
            pytest --junitxml=test-results/pytest/results.xml
          working_directory: tests
      - store_artifacts:
          path: tests/report.html
      - store_test_results:
          path: tests/test-results
  test-ubuntu-focal-kicad6:
    docker:
      - image: admwscki/kicad-kbplacer-primary:6.0.11-focal
    steps: *in-docker-test-steps
  test-ubuntu-lunar-kicad7-0-6:
    docker:
      - image: admwscki/kicad-kbplacer-primary:7.0.6-lunar
    steps: *in-docker-test-steps
  test-ubuntu-focal-kicad7-0-6:
    docker:
      - image: admwscki/kicad-kbplacer-primary:7.0.6-focal
    steps: *in-docker-test-steps
  test-ubuntu-lunar-kicad7-0-7:
    docker:
      - image: admwscki/kicad-kbplacer-primary:7.0.7-lunar
    steps: *in-docker-test-steps
  test-ubuntu-focal-kicad7-0-7:
    docker:
      - image: admwscki/kicad-kbplacer-primary:7.0.7-focal
    steps: *in-docker-test-steps
  test-windows:
    machine:
      image: windows-server-2022-gui:current
      shell: powershell.exe -ExecutionPolicy Bypass
    resource_class: windows.medium
    parameters:
      kicad-version:
        type: string
    steps:
      - checkout
      - run:
          name: Install scoop and KiCad
          command: |
            irm get.scoop.sh -outfile "install.ps1"
            .\install.ps1 -RunAsAdmin -ScoopDir "C:\scoop"
            scoop bucket add extras
            scoop install kicad@<<parameters.kicad-version>>
            scoop cache rm --all
      - run:
          name: Install dependencies
          command: |
            .\.circleci\scripts\use-kicad-python.ps1
            python -m pip install --upgrade pip
            pip install --no-cache-dir -r dev-requirements.txt
      - run:
          name: Run tests
          command: |
            ..\.circleci\scripts\use-kicad-python.ps1
            pytest --junitxml=test-results/pytest/results.xml
          working_directory: tests
      - store_artifacts:
          path: tests/report.html
      - store_test_results:
          path: tests/test-results
  create-pcm-release:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update && sudo apt-get install -y gettext
            python -m pip install --upgrade hatch
      - run:
          name: Create zip package and repository
          command: |
            python -m hatch build --target kicad-package
            python release/package.py
      - store_artifacts:
          path: release/output
      - when: # run only on master or tag
          condition:
            or:
              - << pipeline.git.tag >>
              - equal: [ master, << pipeline.git.branch >> ]
          steps:
            - add_ssh_keys:
                fingerprints:
                  - "d0:4f:c2:dd:e2:fe:9c:25:33:57:3e:fd:09:bd:9e:5c"
            - run:
                name: Deploy repository to github pages
                command: |
                  ./release/deploy.sh
  create-pypi-release:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install hatch==1.7.0
      - run:
          name: Create distribution archive
          command: |
            python -m hatch -v build -t sdist
      - run:
          name: Sanity check result package
          command: |
            python -m venv .env
            . .env/bin/activate
            pip install dist/kbplacer*.tar.gz
            python -c 'from kbplacer.kle_serial import parse_kle; print(parse_kle([["",""]]))'
      - store_artifacts:
          path: dist
  deploy-image:
    machine:
      image: ubuntu-2204:2022.10.2
    steps:
      - checkout
      - run:
          name: Setup environment variables
          command: |
            if [ -z "$CIRCLE_TAG" ]; then
              echo "export TAG=0.7-circleci" >> $BASH_ENV
            else
              # tag branch, cut 'v' prefix (only v prefixed tags should trigger this job)
              echo "export TAG=$(echo $CIRCLE_TAG | cut -c 2-)" >> $BASH_ENV
            fi
            echo "export IMAGE_NAME=kicad-kbplacer" >> $BASH_ENV
      - run:
          name: Build and test docker image
          command: |
            docker build -t admwscki/$IMAGE_NAME:$TAG -f docker/Dockerfile .
            docker run --rm -v $(pwd)/tests:/kicad/tests -v $(pwd)/examples:/kicad/examples \
              -v $(pwd)/dev-requirements.txt:/kicad/tests/dev-requirements.txt \
              -w /kicad/tests admwscki/$IMAGE_NAME:$TAG \
              /bin/bash -c \
              "pip3 install -r dev-requirements.txt && /kicad/.local/bin/pytest -c /dev/null --test-plugin-installation -k test_with_examples"
      - when: # run only on master or tag
          condition:
            or:
              - << pipeline.git.tag >>
              - equal: [ master, << pipeline.git.branch >> ]
          steps:
            - run:
                name: Push docker image
                command: |
                  docker tag admwscki/$IMAGE_NAME:$TAG admwscki/$IMAGE_NAME:latest
                  echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_LOGIN --password-stdin
                  docker push admwscki/$IMAGE_NAME:$TAG
                  docker push admwscki/$IMAGE_NAME:latest
  build-nightly-image:
    machine:
      image: ubuntu-2204:2022.10.2
    steps:
      - checkout
      - run:
          name: Build and push KiCad nightly docker image
          command: |
            docker build -t admwscki/kicad-kbplacer-primary:nightly-lunar -f nightly.Dockerfile .
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_LOGIN --password-stdin
            docker push admwscki/kicad-kbplacer-primary:nightly-lunar
          working_directory: .circleci/images/lunar
  test-linux-kicad-nightly:
    docker:
      - image: admwscki/kicad-kbplacer-primary:nightly-lunar
    steps: *in-docker-test-steps

workflows:
  main:
    jobs:
      - test-ubuntu-lunar-kicad6
      - test-ubuntu-focal-kicad6
      - test-ubuntu-lunar-kicad7-0-6
      - test-ubuntu-focal-kicad7-0-6
      - test-ubuntu-lunar-kicad7-0-7
      - test-ubuntu-focal-kicad7-0-7
      - test-windows:
          name: "test-windows-kicad6"
          kicad-version: "6.0.11"
      - test-windows:
          name: "test-windows-kicad7"
          kicad-version: "7.0.5"
      - create-pcm-release:
          requires: &required-tests
            - test-ubuntu-lunar-kicad6
            - test-ubuntu-focal-kicad6
            - test-ubuntu-lunar-kicad7-0-6
            - test-ubuntu-focal-kicad7-0-6
            - test-ubuntu-lunar-kicad7-0-7
            - test-ubuntu-focal-kicad7-0-7
            - test-windows-kicad6
            - test-windows-kicad7
      - create-pypi-release:
          requires: *required-tests
      - deploy-image:
          requires:
            - create-pcm-release
  kicad-release:
    jobs:
      - create-pcm-release:
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
            branches:
              ignore: /.*/
      - deploy-image:
          requires:
            - create-pcm-release
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - kicad-nightly
    jobs:
      - build-nightly-image
      - test-linux-kicad-nightly:
          requires:
            - build-nightly-image

